//
//  ClipboardManager.swift
//  boringNotch
//
//  Created by Bat-Ireedui on 2026-09-04.
//

import AppKit
import Combine
import CryptoKit
import Defaults
import Foundation

/// Watches the general pasteboard and keeps a persisted history of what was copied.
@MainActor
final class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()

    @Published private(set) var items: [ClipboardItem] = []
    /// Item most recently copied back from the history, used for transient UI feedback.
    @Published var lastCopiedItemID: UUID?

    private(set) var isRunning = false

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private var persistTask: Task<Void, Never>?
    private var cancellables = Set<AnyCancellable>()

    private let storageDirectory: URL
    private let imagesDirectory: URL
    private let historyFileURL: URL
    private let encoder = JSONEncoder()
    private let decoder = JSONDecoder()
    private var imageCache = NSCache<NSString, NSImage>()

    private static let pollInterval: TimeInterval = 0.5
    private static let maxTextLength = 200_000
    private static let maxImageBytes = 25 * 1024 * 1024

    /// Pasteboard types that mark content as sensitive or transient (password managers, etc.).
    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.apple.pasteboard.promised-file-content-type"),
    ]

    private init() {
        let fm = FileManager.default
        let support = try? fm.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
        storageDirectory = (support ?? fm.temporaryDirectory)
            .appendingPathComponent("boringNotch", isDirectory: true)
            .appendingPathComponent("Clipboard", isDirectory: true)
        imagesDirectory = storageDirectory.appendingPathComponent("Images", isDirectory: true)
        historyFileURL = storageDirectory.appendingPathComponent("history.json")
        try? fm.createDirectory(at: imagesDirectory, withIntermediateDirectories: true)

        encoder.outputFormatting = [.prettyPrinted]
        encoder.dateEncodingStrategy = .iso8601
        decoder.dateDecodingStrategy = .iso8601

        lastChangeCount = pasteboard.changeCount
        imageCache.countLimit = 40

        load()

        Defaults.publisher(.clipboardHistoryEnabled)
            .sink { [weak self] change in
                Task { @MainActor in
                    guard let self else { return }
                    if change.newValue {
                        self.start()
                    } else {
                        self.stop()
                        if BoringViewCoordinator.shared.currentView == .clipboard {
                            BoringViewCoordinator.shared.currentView = .home
                        }
                    }
                }
            }
            .store(in: &cancellables)

        Defaults.publisher(.clipboardHistoryLimit)
            .sink { [weak self] _ in
                Task { @MainActor in
                    self?.enforceLimit()
                    self?.schedulePersist()
                }
            }
            .store(in: &cancellables)
    }

    // MARK: - Lifecycle

    func start() {
        guard !isRunning, Defaults[.clipboardHistoryEnabled] else { return }
        isRunning = true
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.poll()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    // MARK: - Public API

    var isEmpty: Bool { items.isEmpty }

    var pinnedItems: [ClipboardItem] { items.filter(\.isPinned) }

    func image(for item: ClipboardItem) -> NSImage? {
        guard case .image(let fileName, _, _) = item.kind else { return nil }
        if let cached = imageCache.object(forKey: fileName as NSString) {
            return cached
        }
        let url = imagesDirectory.appendingPathComponent(fileName)
        guard let image = NSImage(contentsOf: url) else { return nil }
        imageCache.setObject(image, forKey: fileName as NSString)
        return image
    }

    /// Writes the item back to the general pasteboard so it can be pasted with ⌘V.
    func copy(_ item: ClipboardItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .link(let url):
            let pasteboardItem = NSPasteboardItem()
            pasteboardItem.setString(url.absoluteString, forType: .string)
            pasteboardItem.setString(url.absoluteString, forType: .URL)
            pasteboard.writeObjects([pasteboardItem])
        case .image(let fileName, _, _):
            let url = imagesDirectory.appendingPathComponent(fileName)
            if let data = try? Data(contentsOf: url) {
                pasteboard.setData(data, forType: .png)
                if let tiff = NSImage(data: data)?.tiffRepresentation {
                    pasteboard.setData(tiff, forType: .tiff)
                }
            }
        case .files:
            pasteboard.writeObjects(item.fileURLs as [NSURL])
        }
        // Do not re-capture our own write.
        lastChangeCount = pasteboard.changeCount

        moveToTop(item.id)
        lastCopiedItemID = item.id
        schedulePersist()
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        enforceLimit()
        schedulePersist()
    }

    func remove(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        let removed = items.remove(at: index)
        deleteBackingFile(for: removed)
        schedulePersist()
    }

    /// Removes every unpinned item. Pass `includingPinned: true` to wipe everything.
    func clear(includingPinned: Bool = false) {
        let toRemove = items.filter { includingPinned || !$0.isPinned }
        toRemove.forEach(deleteBackingFile(for:))
        items.removeAll { includingPinned || !$0.isPinned }
        schedulePersist()
    }

    // MARK: - Polling

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        capture()
    }

    private func capture() {
        guard let types = pasteboard.types, !types.isEmpty else { return }
        if types.contains(where: { Self.ignoredTypes.contains($0) }) { return }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        if let item = captureFiles(source: source)
            ?? captureImage(source: source)
            ?? captureText(source: source)
        {
            insert(item)
        }
    }

    private func captureFiles(source: String?) -> ClipboardItem? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              !urls.isEmpty
        else { return nil }
        let paths = urls.map(\.path)
        return ClipboardItem(
            kind: .files(paths),
            fingerprint: "files:" + paths.joined(separator: "\n"),
            sourceBundleID: source
        )
    }

    private func captureImage(source: String?) -> ClipboardItem? {
        guard Defaults[.clipboardCaptureImages] else { return nil }
        // Prefer PNG, fall back to TIFF. Skip when the pasteboard also carries real text,
        // which usually means a rich-text copy that happens to include an image representation.
        // A lone URL alongside the image (Safari "Copy Image") still counts as an image.
        if let text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
           !text.isEmpty,
           text.contains(where: \.isWhitespace) || URL(string: text)?.scheme == nil
        {
            return nil
        }

        var data = pasteboard.data(forType: .png)
        if data == nil, let tiff = pasteboard.data(forType: .tiff) {
            data = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
        }
        guard let pngData = data, pngData.count <= Self.maxImageBytes,
              let rep = NSBitmapImageRep(data: pngData)
        else { return nil }

        let digest = SHA256.hash(data: pngData).map { String(format: "%02x", $0) }.joined()
        let fingerprint = "image:" + digest

        // Re-use the existing file when the exact same image is copied again.
        if let existing = items.first(where: { $0.fingerprint == fingerprint }),
           case .image(let fileName, let w, let h) = existing.kind
        {
            return ClipboardItem(kind: .image(fileName: fileName, width: w, height: h), fingerprint: fingerprint, sourceBundleID: source)
        }

        let fileName = UUID().uuidString + ".png"
        let url = imagesDirectory.appendingPathComponent(fileName)
        do {
            try pngData.write(to: url, options: .atomic)
        } catch {
            NSLog("Clipboard: failed to store image: \(error.localizedDescription)")
            return nil
        }
        return ClipboardItem(
            kind: .image(fileName: fileName, width: rep.pixelsWide, height: rep.pixelsHigh),
            fingerprint: fingerprint,
            sourceBundleID: source
        )
    }

    private func captureText(source: String?) -> ClipboardItem? {
        guard let raw = pasteboard.string(forType: .string) else { return nil }
        let text = String(raw.prefix(Self.maxTextLength))
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }

        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.contains(where: \.isWhitespace),
           let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(), ["http", "https"].contains(scheme),
           url.host != nil
        {
            return ClipboardItem(kind: .link(url), fingerprint: "link:" + trimmed, sourceBundleID: source)
        }
        return ClipboardItem(kind: .text(text), fingerprint: "text:" + text, sourceBundleID: source)
    }

    // MARK: - Mutation helpers

    private func insert(_ item: ClipboardItem) {
        var newItem = item
        if let index = items.firstIndex(where: { $0.fingerprint == item.fingerprint }) {
            let existing = items.remove(at: index)
            newItem.isPinned = existing.isPinned
        }
        items.insert(newItem, at: 0)
        enforceLimit()
        schedulePersist()
    }

    private func moveToTop(_ id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        var item = items.remove(at: index)
        item.createdAt = Date()
        items.insert(item, at: 0)
    }

    private func enforceLimit() {
        let limit = max(1, Defaults[.clipboardHistoryLimit])
        guard items.count > limit else { return }
        var overflow = items.count - limit
        var index = items.count - 1
        while overflow > 0, index >= 0 {
            if !items[index].isPinned {
                deleteBackingFile(for: items[index])
                items.remove(at: index)
                overflow -= 1
            }
            index -= 1
        }
    }

    private func deleteBackingFile(for item: ClipboardItem) {
        guard case .image(let fileName, _, _) = item.kind else { return }
        // Another item may share the same file when the same image was copied twice.
        let stillReferenced = items.contains { other in
            if other.id == item.id { return false }
            if case .image(let name, _, _) = other.kind { return name == fileName }
            return false
        }
        guard !stillReferenced else { return }
        imageCache.removeObject(forKey: fileName as NSString)
        try? FileManager.default.removeItem(at: imagesDirectory.appendingPathComponent(fileName))
    }

    // MARK: - Persistence

    private func load() {
        guard let data = try? Data(contentsOf: historyFileURL),
              let decoded = try? decoder.decode([ClipboardItem].self, from: data)
        else { return }
        let fm = FileManager.default
        items = decoded.filter { item in
            if case .image(let fileName, _, _) = item.kind {
                return fm.fileExists(atPath: imagesDirectory.appendingPathComponent(fileName).path)
            }
            return true
        }
        enforceLimit()
    }

    private func schedulePersist() {
        persistTask?.cancel()
        let snapshot = items
        persistTask = Task { [weak self] in
            try? await Task.sleep(for: .milliseconds(300))
            guard !Task.isCancelled, let self else { return }
            self.persist(snapshot)
        }
    }

    private func persist(_ snapshot: [ClipboardItem]) {
        do {
            let data = try encoder.encode(snapshot)
            try data.write(to: historyFileURL, options: .atomic)
        } catch {
            NSLog("Clipboard: failed to persist history: \(error.localizedDescription)")
        }
    }
}
